In [1]:
import pandas as pd

In [7]:
#API key for geocoder in .env
from dotenv import load_dotenv
import os
!touch .env
load_dotenv()

True

In [8]:
api_key=os.getenv('api_key')

In [ ]:
#All polling stations abroad in 2024

df_2024 = pd.read_excel(r'2024.xlsx', sheet_name=0)
df_2024.head()

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб
0,320010001,NaN,Извън страната,Австралия,Канбера,Канбера (Посолство),0,0,0,0,0
1,320010002,NaN,Извън страната,Австралия,Бризбън,Бризбън,0,0,0,0,0
2,320010003,NaN,Извън страната,Австралия,Мелбърн,Мелбърн,0,0,0,0,0
3,320010004,NaN,Извън страната,Австралия,"Пърт, AU",Пърт,0,0,0,0,0
4,320010005,NaN,Извън страната,Австралия,Сидни,Сидни,0,0,0,0,0

In [3]:
#In which non-EU countries there were more than 20 polling stations

df_2024.Община.value_counts()

Община
Турция                                                  168
Обединено кралство Великобритания и Северна Ирландия    112
Германия ФР                                              66
Испания                                                  64
САЩ                                                      53
Италия                                                   27
Нидерландия                                              25
Гърция                                                   23
Франция                                                  17
Австрия                                                  16
Белгия                                                   16
Канада                                                   15
Швейцария                                                11
Дания                                                     9
Кипър                                                     8
Норвегия                                                  8
Молдова                                                   7
Австралия                                                 5
Ирландия                                                  5
Република Северна Македония                               5
Албания                                                   4
Сърбия                                                    4
Португалия                                                3
Република Южна Африка                                     3
Финландия                                                 3
Чехия                                                     3
Швеция                                                    3
Китай                                                     2
Люксембург                                                2
Малта                                                     2
ОАЕ                                                       2
Полша                                                     2
Русия                                                     2
Алжир                                                     1
Армения                                                   1
Беларус                                                   1
Босна и Херцеговина                                       1
Грузия                                                    1
Египет                                                    1
Исландия                                                  1
Йордания                                                  1
Катар                                                     1
Косово                                                    1
Кувейт                                                    1
Мароко                                                    1
Нова Зеландия                                             1
Република Корея                                           1
Румъния                                                   1
Саудитска Арабия                                          1
Сингапур                                                  1
Словакия                                                  1
Словения                                                  1
Тунис                                                     1
Унгария                                                   1
Хърватия                                                  1
Черна гора                                                1
Япония                                                    1
Name: count, dtype: int64

In [4]:
#All polling stations in Turkey in 2024

df_Turkey_2024 = df_2024.query("Община == 'Турция'")
df_Turkey_2024

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб
510,321180511,NaN,Извън страната,Турция,Анкара,Анкара (Посолство),0,0,0,0,0
511,321180512,NaN,Извън страната,Турция,Анкара,"Анкара, общ. Пурсаклар, кв. Тепебашъ",0,1,0,0,0
512,321180513,NaN,Извън страната,Турция,Анкара,"Анкара, Синджан, Тандоган",0,0,0,0,0
513,321180514,NaN,Извън страната,Турция,Адана,Адана,0,0,0,0,0
514,321180515,NaN,Извън страната,Турция,Айдън,Айдън,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
673,321180674,NaN,Извън страната,Турция,"Чорлу, Шейхсинан","Чорлу, кв. Шейхсинан 5",0,1,0,0,0
674,321180675,NaN,Извън страната,Турция,Ялова,Ялова 1,0,1,0,0,0
675,321180676,NaN,Извън страната,Турция,Ялова,Ялова 2,0,1,0,0,0
676,321180677,NaN,Извън страната,Турция,Ялова,"Ялова, Алтънова (Субашъ)",0,0,0,0,0
677,321180678,NaN,Извън страната,Турция,Ялова,"Ялова, Чифтликкьой",0,1,0,0,0

In [5]:
#New df with only locations

df_Turkey_2024_locations = df_Turkey_2024[['Община','Населено място', 'Адрес']]
df_Turkey_2024_locations

     Община    Населено място                                 Адрес
510  Турция            Анкара                    Анкара (Посолство)
511  Турция            Анкара  Анкара, общ. Пурсаклар, кв. Тепебашъ
512  Турция            Анкара             Анкара, Синджан, Тандоган
513  Турция             Адана                                 Адана
514  Турция            Айдън                                 Айдън
..      ...               ...                                   ...
673  Турция  Чорлу, Шейхсинан                Чорлу, кв. Шейхсинан 5
674  Турция             Ялова                               Ялова 1
675  Турция             Ялова                               Ялова 2
676  Турция             Ялова              Ялова, Алтънова (Субашъ)
677  Турция             Ялова                    Ялова, Чифтликкьой

[168 rows x 3 columns]

In [6]:
df_Turkey_2024_locations.to_csv("df_Turkey_2024_locations.csv", index=False)

In [13]:
#Geocode 2024 locations in Turkey

import geocoder
import csv

with open('df_Turkey_2024_locations.csv', encoding='utf8') as fp:
    data = list(csv.DictReader(fp))

data[0]

{'Община': 'Турция', 'Населено място': 'Анкара', 'Адрес': 'Анкара (Посолство)'}

In [10]:
for location in data:
    address = f"{location['Адрес']}, {location['Населено място']}, {location['Община']}"
    g = geocoder.google(address, key=api_key)
    
    if g.latlng:
        location['lat'] = g.latlng[0]
        location['lon'] = g.latlng[1]
    else:
        print("Could not geocode:", address)
        location['lat'] = None
        location['lon'] = None

print(data [0])

{'Община': 'Турция', 'Населено място': 'Анкара', 'Адрес': 'Анкара (Посолство)', 'lat': 39.9333635, 'lon': 32.8597419}

In [11]:
with open('df_Turkey_2024_geocoded.csv', 'w', encoding='utf-8', newline='') as fp:
    fieldnames=['Община','Населено място','Адрес','lat', 'lon']

    writer = csv.DictWriter(fp, fieldnames=fieldnames)
    writer.writeheader()
    for row in data:
        writer.writerow(row)

In [12]:
#All polling stations in the UK in 2024

df_UK_2024 = df_2024.query("Община == 'Обединено кралство Великобритания и Северна Ирландия'")
df_UK_2024

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб
319,320920320,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Абърдийн,Абърдийн,0,0,0,0,0
320,320920321,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Арма,Арма,0,0,0,0,0
321,320920322,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Базилдън,Базилдън,0,0,0,0,0
322,320920323,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Бедфорд,Бедфорд,0,0,0,0,0
323,320920324,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Бейзингстоук,Бейзингстоук,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
426,320920427,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Хъл,Хъл,0,0,0,0,0
427,320920428,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Чатъм,Чатъм,0,1,0,0,0
428,320920429,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Челмсфорд,Челмсфорд,0,0,0,0,0
429,320920430,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Честър,Честър,0,0,0,0,0
430,320920431,NaN,Извън страната,Обединено кралство Великобритания и Северна Ир...,Шефилд,Шефилд,0,0,0,0,0

In [14]:
df_UK_2024_locations = df_UK_2024[['Община','Населено място', 'Адрес']]
df_UK_2024_locations

,Община,Населено място,Адрес
319,Обединено кралство Великобритания и Северна Ир...,Абърдийн,Абърдийн
320,Обединено кралство Великобритания и Северна Ир...,Арма,Арма
321,Обединено кралство Великобритания и Северна Ир...,Базилдън,Базилдън
322,Обединено кралство Великобритания и Северна Ир...,Бедфорд,Бедфорд
323,Обединено кралство Великобритания и Северна Ир...,Бейзингстоук,Бейзингстоук
...,...,...,...
426,Обединено кралство Великобритания и Северна Ир...,Хъл,Хъл
427,Обединено кралство Великобритания и Северна Ир...,Чатъм,Чатъм
428,Обединено кралство Великобритания и Северна Ир...,Челмсфорд,Челмсфорд
429,Обединено кралство Великобритания и Северна Ир...,Честър,Честър
430,Обединено кралство Великобритания и Северна Ир...,Шефилд,Шефилд

In [15]:
df_UK_2024_locations.to_csv("df_UK_2024_locations.csv", index=False)

In [16]:
#Geocode 2024 locations in the UK

with open('df_UK_2024_locations.csv', encoding='utf8') as fp:
    data1 = list(csv.DictReader(fp))

data1[0]

{'Община': 'Обединено кралство Великобритания и Северна Ирландия',
 'Населено място': 'Абърдийн',
 'Адрес': 'Абърдийн'}

In [18]:
for location in data1:
    address = f"{location['Адрес']}, {location['Населено място']}, {location['Община']}"
    g = geocoder.google(address, key=api_key)
    
    if g.latlng:
        location['lat'] = g.latlng[0]
        location['lon'] = g.latlng[1]
    else:
        print("Could not geocode:", address)
        location['lat'] = None
        location['lon'] = None

print(data1 [0])

{'Община': 'Обединено кралство Великобритания и Северна Ирландия', 'Населено място': 'Абърдийн', 'Адрес': 'Абърдийн', 'lat': 57.1498891, 'lon': -2.0937528}

In [19]:
with open('df_UK_2024_geocoded.csv', 'w', encoding='utf-8', newline='') as fp:
    fieldnames=['Община','Населено място','Адрес','lat', 'lon']

    writer = csv.DictWriter(fp, fieldnames=fieldnames)
    writer.writeheader()
    for row in data1:
        writer.writerow(row)

In [20]:
#All polling stations in the US in 2024

df_US_2024 = df_2024.query("Община == 'САЩ'")
df_US_2024.head()

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб
444,321070445,NaN,Извън страната,САЩ,"Флорида, Алтамонт Спрингс - Орландо","Алтамонт Спрингс - Орландо, Флорида",0,0,0,0,0
445,321070446,NaN,Извън страната,САЩ,"Илинойс, Арлингтън Хайтс","Арлингтън Хайтс, Илинойс, Културен център “Маг...",0,1,0,0,0
446,321070447,NaN,Извън страната,САЩ,"Джорджия, Атланта","Атланта, Джорджия",0,0,0,0,0
447,321070448,NaN,Извън страната,САЩ,"Ню Джърси, Атлантик Сити, Нортфийлд","Атлантик Сити, Нортфийлд, Ню Джърси",0,0,0,0,0
448,321070449,NaN,Извън страната,САЩ,"Масачузетс, Бостън",Бостън - Билрика,0,0,0,0,0

In [23]:
df_US_2024_locations = df_US_2024[['Община','Населено място', 'Адрес']]
df_US_2024_locations.head()

,Община,Населено място,Адрес
444,САЩ,"Флорида, Алтамонт Спрингс - Орландо","Алтамонт Спрингс - Орландо, Флорида"
445,САЩ,"Илинойс, Арлингтън Хайтс","Арлингтън Хайтс, Илинойс, Културен център “Маг..."
446,САЩ,"Джорджия, Атланта","Атланта, Джорджия"
447,САЩ,"Ню Джърси, Атлантик Сити, Нортфийлд","Атлантик Сити, Нортфийлд, Ню Джърси"
448,САЩ,"Масачузетс, Бостън",Бостън - Билрика

In [22]:
df_US_2024_locations.to_csv("df_US_2024_locations.csv", index=False)

In [24]:
#Geocode 2024 locations in the US

with open('df_US_2024_locations.csv', encoding='utf8') as fp:
    data2 = list(csv.DictReader(fp))

data2[0]

{'Община': 'САЩ',
 'Населено място': 'Флорида, Алтамонт Спрингс - Орландо',
 'Адрес': 'Алтамонт Спрингс - Орландо, Флорида'}

In [25]:
for location in data2:
    address = f"{location['Адрес']}, {location['Населено място']}, {location['Община']}"
    g = geocoder.google(address, key=api_key)
    
    if g.latlng:
        location['lat'] = g.latlng[0]
        location['lon'] = g.latlng[1]
    else:
        print("Could not geocode:", address)
        location['lat'] = None
        location['lon'] = None

print(data2 [0])

{'Община': 'САЩ', 'Населено място': 'Флорида, Алтамонт Спрингс - Орландо', 'Адрес': 'Алтамонт Спрингс - Орландо, Флорида', 'lat': 28.6611089, 'lon': -81.3656242}

In [26]:
with open('df_US_2024_geocoded.csv', 'w', encoding='utf-8', newline='') as fp:
    fieldnames=['Община','Населено място','Адрес','lat', 'lon']

    writer = csv.DictWriter(fp, fieldnames=fieldnames)
    writer.writeheader()
    for row in data2:
        writer.writerow(row)

In [ ]:
#All polling stations abroad in 2026

df_2026 = pd.read_excel(r'2026.xlsx', sheet_name=0)
df_2026.head()

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб,Географска ширина,Географска дължина
0,320010001,NaN,Извън страната,Австралия,Канбера,"АВСТРАЛИЯ, Канбера (Посолство)",0,0,0,0,0,-35.358385,149.108145
1,320010002,NaN,Извън страната,Австралия,Аделаида,"АВСТРАЛИЯ, Аделаида",0,0,0,0,0,-34.911800,138.514151
2,320010003,NaN,Извън страната,Австралия,Бризбън,"АВСТРАЛИЯ, Бризбън",0,0,0,0,0,-27.488698,153.027860
3,320010004,NaN,Извън страната,Австралия,Мелбърн,"АВСТРАЛИЯ, Мелбърн",0,0,0,0,0,-37.775804,144.998256
4,320010005,NaN,Извън страната,Австралия,Пърт,"АВСТРАЛИЯ, Пърт",0,0,0,0,0,-31.889421,115.921361

In [28]:
#How many polling stations in each country

df_2026.Община.value_counts()

Община
Германия               70
Испания                67
Обединено кралство     28
Италия                 27
Турция                 27
Гърция                 26
Нидерландия            24
САЩ                    24
Франция                19
Австрия                17
Белгия                 17
Канада                 17
Швейцария              11
Молдова                10
Дания                   9
Норвегия                9
Кипър                   8
Ирландия                7
Австралия               6
Северна Македония       5
Сърбия                  5
Швеция                  5
Албания                 4
Португалия              4
Финландия               4
Южна Африка             3
Чехия                   3
Китай                   2
Люксембург              2
Малта                   2
Нова Зеландия           2
Полша                   2
Русия                   2
Унгария                 2
Хърватия                2
Япония                  2
Азербайджан             1
Алжир                   1
Аржентина               1
Армения                 1
Беларус                 1
Босна и Херцеговина     1
Бразилия                1
Грузия                  1
Египет                  1
Исландия                1
Косово                  1
Мароко                  1
Република Корея         1
Румъния                 1
Сингапур                1
Словакия                1
Словения                1
Тунис                   1
Черна гора              1
Name: count, dtype: int64

In [29]:
#All polling stations in Turkey in 2026

df_Turkey_2026 = df_2026.query("Община == 'Турция'")
df_Turkey_2026.head()

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб,Географска ширина,Географска дължина
417,321180418,NaN,Извън страната,Турция,Анкара,"ТУРЦИЯ, Анкара (Посолство) 1",0,0,0,0,0,39.908909,32.856212
418,321180419,NaN,Извън страната,Турция,Анкара,"ТУРЦИЯ, Анкара (Посолство) 2",0,0,0,0,0,39.908909,32.856212
419,321180420,NaN,Извън страната,Турция,Анкара,"ТУРЦИЯ, Анкара (Посолство) 3",0,0,0,0,0,39.908909,32.856212
420,321180421,NaN,Извън страната,Турция,Бурса,"ТУРЦИЯ, Бурса (Консулска канцелария)",0,1,0,0,0,40.225720,29.007433
421,321180422,NaN,Извън страната,Турция,Бурса,"ТУРЦИЯ, Бурса, Инегьол",0,1,0,0,0,40.190963,29.206151

In [30]:
#New df with only locations

df_Turkey_2026_locations = df_Turkey_2026[['Населено място', 'Географска ширина','Географска дължина']]
df_Turkey_2026_locations

    Населено място  Географска ширина  Географска дължина
417         Анкара          39.908909           32.856212
418         Анкара          39.908909           32.856212
419         Анкара          39.908909           32.856212
420          Бурса          40.225720           29.007433
421          Бурса          40.190963           29.206151
422          Бурса          40.212020           29.095391
423          Бурса          40.216651           28.813332
424          Бурса          40.271982           29.087472
425          Бурса          40.252489           28.975055
426          Гебзе          40.803716           29.442850
427         Ергене          41.183163           27.773208
428      Ескишехир          39.748309           30.536588
429          Измир          38.483064           27.203140
430          Измир          38.372312           27.167921
431          Измир          38.302258           27.176565
432          Измир          38.285846           27.127398
433       Истанбул          41.069730           29.029433
434       Истанбул          41.069730           29.029433
435       Истанбул          40.983447           28.724687
436       Истанбул          41.071127           28.886308
437       Истанбул          40.998213           28.827977
438       Истанбул          41.046656           28.644267
439     Люлебургаз          41.399704           27.363851
440          Одрин          41.674063           26.560127
441          Чорлу          41.138838           27.800376
442          Чорлу          41.155907           27.790736
443          Ялова          40.656423           29.287627

In [31]:
df_Turkey_2026_locations.to_csv("df_Turkey_2026_locations.csv", index=False)

In [32]:
#All polling stations in the UK in 2026

df_UK_2026 = df_2026.query("Община == 'Обединено кралство'")
df_UK_2026.head()

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб,Географска ширина,Географска дължина
338,320920339,NaN,Извън страната,Обединено кралство,Единбург,ОБЕДИНЕНО КРАЛСТВО ВЕЛИКОБРИТАНИЯ И СЕВЕРНА ИР...,0,1,0,0,0,55.951050,-3.177970
339,320920340,NaN,Извън страната,Обединено кралство,Лондон,ОБЕДИНЕНО КРАЛСТВО ВЕЛИКОБРИТАНИЯ И СЕВЕРНА ИР...,0,1,0,0,0,51.499986,-0.179557
340,320920341,NaN,Извън страната,Обединено кралство,Лондон,ОБЕДИНЕНО КРАЛСТВО ВЕЛИКОБРИТАНИЯ И СЕВЕРНА ИР...,0,1,0,0,0,51.499986,-0.179557
341,320920342,NaN,Извън страната,Обединено кралство,Лондон,ОБЕДИНЕНО КРАЛСТВО ВЕЛИКОБРИТАНИЯ И СЕВЕРНА ИР...,0,1,0,0,0,51.499986,-0.179557
342,320920343,NaN,Извън страната,Обединено кралство,Лондон,ОБЕДИНЕНО КРАЛСТВО ВЕЛИКОБРИТАНИЯ И СЕВЕРНА ИР...,0,0,0,0,0,51.499986,-0.179557

In [33]:
df_UK_2026_locations = df_UK_2026[['Населено място', 'Географска ширина','Географска дължина']]
df_UK_2026_locations

    Населено място  Географска ширина  Географска дължина
338       Единбург          55.951050           -3.177970
339         Лондон          51.499986           -0.179557
340         Лондон          51.499986           -0.179557
341         Лондон          51.499986           -0.179557
342         Лондон          51.499986           -0.179557
343         Лондон          51.499986           -0.179557
344         Лондон          51.499986           -0.179557
345         Лондон          51.499986           -0.179557
346           Арма          54.357042           -6.660646
347      Бирмингам          52.475477           -1.900310
348        Бристол          51.455313           -2.593393
349      Кеймбридж          52.194586            0.135531
350         Лондон          51.539018            0.078246
351         Лондон          51.411991            0.021369
352         Лондон          51.513402           -0.308024
353         Лондон          51.616150           -0.109195
354         Лондон          51.549179           -0.006874
355         Лондон          51.391005           -0.320819
356         Лондон          51.419358           -0.194700
357         Лондон          51.581356           -0.034600
358          Лутън          51.875976           -0.418699
359      Манчестър          53.505521           -2.258781
360      Мейдстоун          51.255488            0.543391
361          Норич          52.631999            1.298716
362       Нотингам          52.970169           -1.153225
363         Рединг          51.456373           -0.967373
364    Саутхемптън          50.899428           -1.409408
365            Хъл          53.747470           -0.348148

In [34]:
df_UK_2026_locations.to_csv("df_UK_2026_locations.csv", index=False)

In [35]:
#All polling stations in the US in 2026

df_US_2026 = df_2026.query("Община == 'САЩ'")
df_US_2026.head()

,Номер на СИК,ЕКАТТЕ,Област,Община,Населено място,Адрес,Подвижна,С машина,Лечебно заведение,Място за задържане,Кораб,Географска ширина,Географска дължина
379,321070380,NaN,Извън страната,САЩ,"Атланта, Джорджия","САЩ, Атланта, Джорджия",0,1,0,0,0,33.916126,-84.467366
380,321070381,NaN,Извън страната,САЩ,"Бостън, Масачузетс","САЩ, Бостън, Масачузетс",0,1,0,0,0,42.357893,-71.184259
381,321070382,NaN,Извън страната,САЩ,"Брумал, Пенсилвания","САЩ, Брумал, Пенсилвания",0,0,0,0,0,39.980998,-75.361744
382,321070383,NaN,Извън страната,САЩ,Вашингтон,"САЩ, Вашингтон (Посолство)",0,1,0,0,0,38.912376,-77.048553
383,321070384,NaN,Извън страната,САЩ,"Далас, Тексас","САЩ, Далас, Тексас",0,0,0,0,0,32.927761,-96.896676

In [36]:
df_US_2026_locations = df_US_2026[['Населено място', 'Географска ширина','Географска дължина']]
df_US_2026_locations

,Населено място,Географска ширина,Географска дължина
379,"Атланта, Джорджия",33.916126,-84.467366
380,"Бостън, Масачузетс",42.357893,-71.184259
381,"Брумал, Пенсилвания",39.980998,-75.361744
382,Вашингтон,38.912376,-77.048553
383,"Далас, Тексас",32.927761,-96.896676
384,"Денвър, Колорадо",39.691279,-104.939926
385,"Дес Плейнс, Илинойс",42.027246,-87.893507
386,"Дес Плейнс, Илинойс",42.038122,-87.890934
387,"Лас Вегас, Невада",36.108398,-115.261609
388,Лос Анджелис,34.048048,-118.462175
389,"Маунт Проспект, Илинойс",42.042461,-87.946081
390,"Маями - Форт Лодърдейл, Флорида",26.169741,-80.099572
391,Ню Йорк,40.764608,-73.967536
392,"Питсбърг, Пенсилвания",40.401762,-79.917790
393,"Сан Диего, Калифорния",32.897578,-117.124631
394,"Сейнт Питърсбърг, Флорида",27.856854,-82.649339
395,"Сиатъл, Вашингтон",47.632803,-122.357367
396,"Синсинати, Охайо",39.183922,-84.423489
397,"Сънивейл - Сан Хосе, Северна Калифорния",37.349908,-122.057643
398,"Финикс, Аризона",33.487302,-112.026979
399,"Хаянис, Масачузетс",41.674118,-70.309879
400,Чикаго,41.896000,-87.623806
401,"Шамбург, Илинойс",42.057095,-88.046659
402,"Шарлът-Матюс, Северна Каролина",35.144781,-80.719020

In [37]:
df_US_2026_locations.to_csv("df_US_2026_locations.csv", index=False)

In [ ]:
df_2024_votes = pd.read_excel(r'2024.xlsx', sheet_name=3)
df_2024_votes.head()

,Номер на СИК,ЕКАТТЕ,Област,Община/Държава,Населено място,Образец,т. А,т. 1,т. 2,т. 3,т. 4 а),т. 4 б),т. 5 (т. 11),т. 6,т. 7 (т. 12),т. 9 (т. 14)
0,320010001,NaN,Извън страната,Австралия,Канбера,Х,200.0,0.0,24.0,24.0,175.0,1.0,24,2.0,1,21
1,320010002,NaN,Извън страната,Австралия,Бризбън,Х,200.0,47.0,12.0,43.0,156.0,1.0,43,2.0,2,39
2,320010003,NaN,Извън страната,Австралия,Мелбърн,Х,300.0,3.0,86.0,88.0,211.0,1.0,88,0.0,2,86
3,320010004,NaN,Извън страната,Австралия,"Пърт, AU",Х,200.0,16.0,47.0,63.0,136.0,1.0,63,1.0,1,61
4,320010005,NaN,Извън страната,Австралия,Сидни,Х,300.0,25.0,109.0,126.0,171.0,3.0,126,2.0,1,123

In [46]:
#From data dict: 3.	Брой на гласувалите избиратели според положените подписи в списъка за гласуване извън страната, включително и подписите
#в допълнителната страница (под чертата)	

df_2024_votes.groupby(by="Община/Държава")['т. 3'].sum()

Община/Държава
Австралия                                                 344.0
Австрия                                                  4388.0
Албания                                                   329.0
Алжир                                                      31.0
Армения                                                    49.0
Беларус                                                    34.0
Белгия                                                   3766.0
Босна и Херцеговина                                        30.0
Германия ФР                                             20877.0
Грузия                                                     39.0
Гърция                                                   2627.0
Дания                                                    1426.0
Египет                                                     38.0
Ирландия                                                  677.0
Исландия                                                  101.0
Испания                                                 10898.0
Италия                                                   3162.0
Йордания                                                   38.0
Канада                                                   2765.0
Катар                                                      61.0
Кипър                                                    1503.0
Китай                                                     107.0
Косово                                                    121.0
Кувейт                                                     67.0
Люксембург                                                635.0
Малта                                                     459.0
Мароко                                                     33.0
Молдова                                                   523.0
Нидерландия                                              5921.0
Нова Зеландия                                              84.0
Норвегия                                                  949.0
ОАЕ                                                       333.0
Обединено кралство Великобритания и Северна Ирландия    21729.0
Полша                                                     266.0
Португалия                                                348.0
Република Корея                                            32.0
Република Северна Македония                               178.0
Република Южна Африка                                     282.0
Румъния                                                   200.0
Русия                                                     258.0
САЩ                                                      8924.0
Саудитска Арабия                                           21.0
Сингапур                                                   76.0
Словакия                                                  146.0
Словения                                                  102.0
Сърбия                                                   1055.0
Тунис                                                      22.0
Турция                                                  47807.0
Унгария                                                   211.0
Финландия                                                 405.0
Франция                                                  3116.0
Хърватия                                                   82.0
Черна гора                                                 16.0
Чехия                                                     762.0
Швейцария                                                2213.0
Швеция                                                    665.0
Япония                                                     98.0
Name: т. 3, dtype: float64

In [47]:
df_2024_votes['т. 3'].sum()

np.float64(151429.0)

In [ ]:
df_2026_votes = pd.read_excel(r'2026.xlsx', sheet_name=3)
df_2026_votes.head()

,Номер на СИК,ЕКАТТЕ,Област,Община/Държава,Населено място,Образец,т. А,т. Б,т. 1,т. 2,т. 3,т. 4,т. 5 (т. 11),т. 6,т. 7 (т. 12),т. 9 (т. 14)
0,320010001,NaN,Извън страната,Австралия,Канбера,Х,200.0,1.0,31.0,32.0,167.0,1.0,32,0.0,0,32
1,320010002,NaN,Извън страната,Австралия,Аделаида,Х,200.0,48.0,19.0,54.0,143.0,3.0,54,2.0,0,52
2,320010003,NaN,Извън страната,Австралия,Бризбън,Х,200.0,59.0,54.0,102.0,97.0,1.0,102,1.0,2,99
3,320010004,NaN,Извън страната,Австралия,Мелбърн,Х,300.0,59.0,102.0,148.0,150.0,2.0,148,1.0,2,145
4,320010005,NaN,Извън страната,Австралия,Пърт,Х,200.0,51.0,37.0,80.0,119.0,1.0,80,0.0,1,79

In [49]:
#From dictionry: 2.	Брой на гласувалите избиратели според положените подписи в списъка за гласуване извън страната,
#включително и подписите в допълнителната страница (под чертата)

df_2026_votes.groupby(by="Община/Държава")['т. 2'].sum()

Община/Държава
Австралия                637.0
Австрия                 6993.0
Азербайджан               32.0
Албания                  494.0
Алжир                     58.0
Аржентина                 51.0
Армения                   47.0
Беларус                   36.0
Белгия                  6580.0
Босна и Херцеговина       45.0
Бразилия                  40.0
Германия               37593.0
Грузия                    47.0
Гърция                  5164.0
Дания                   2322.0
Египет                    67.0
Ирландия                1397.0
Исландия                 171.0
Испания                19558.0
Италия                  6524.0
Канада                  3929.0
Кипър                   2974.0
Китай                    197.0
Косово                   223.0
Люксембург               920.0
Малта                    774.0
Мароко                    54.0
Молдова                 1015.0
Нидерландия             9817.0
Нова Зеландия            148.0
Норвегия                1393.0
Обединено кралство     27635.0
Полша                    640.0
Португалия               677.0
Република Корея           57.0
Румъния                  316.0
Русия                    444.0
САЩ                     9888.0
Северна Македония        463.0
Сингапур                 102.0
Словакия                 352.0
Словения                 158.0
Сърбия                  2207.0
Тунис                     22.0
Турция                 30229.0
Унгария                  701.0
Финландия                603.0
Франция                 5229.0
Хърватия                 215.0
Черна гора                19.0
Чехия                   1631.0
Швейцария               3513.0
Швеция                  1245.0
Южна Африка              400.0
Япония                   235.0
Name: т. 2, dtype: float64

In [53]:
df_2026_votes['т. 2'].sum()

np.float64(196281.0)

In [56]:
votes_2024 = df_2024_votes.groupby("Община/Държава")["т. 3"].sum()
votes_2026 = df_2026_votes.groupby("Община/Държава")["т. 2"].sum()

df = pd.DataFrame()

df["2026"] = [
    votes_2026["Турция"],
    votes_2026["Обединено кралство"],
    votes_2026["САЩ"],
    df_2026_votes["т. 2"].sum()
]

df["2024"] = [
    votes_2024["Турция"],
    votes_2024["Обединено кралство Великобритания и Северна Ирландия"],
    votes_2024["САЩ"],
    df_2024_votes["т. 3"].sum()
]

df.index = ["Turkey", "UK", "US", "All abroad"]

print(df)

                2026      2024
Turkey       30229.0   47807.0
UK           27635.0   21729.0
US            9888.0    8924.0
All abroad  196281.0  151429.0

In [57]:
df.to_csv("comparison2026_2024.csv")